// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2UBYoVzqpZeEh-gFcKx1aMxy5XYYH7k',
    appId: '1:917866347943:web:aa89b7ecb780aa20c20a82',
    messagingSenderId: '917866347943',
    projectId: 'v-news-ecea2',
    authDomain: 'v-news-ecea2.firebaseapp.com',
    storageBucket: 'v-news-ecea2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfULXl5E37ykwNc-HF4cRbSJNLo4txTqM',
    appId: '1:917866347943:android:d1932522e423fbd7c20a82',
    messagingSenderId: '917866347943',
    projectId: 'v-news-ecea2',
    storageBucket: 'v-news-ecea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQZJb3NpZ0KJaLj0P4poudA-CC8PGKP8',
    appId: '1:917866347943:ios:bb200070405843a2c20a82',
    messagingSenderId: '917866347943',
    projectId: 'v-news-ecea2',
    storageBucket: 'v-news-ecea2.appspot.com',
    iosBundleId: 'com.example.vnewszz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQZJb3NpZ0KJaLj0P4poudA-CC8PGKP8',
    appId: '1:917866347943:ios:106caec5a0571a2cc20a82',
    messagingSenderId: '917866347943',
    projectId: 'v-news-ecea2',
    storageBucket: 'v-news-ecea2.appspot.com',
    iosBundleId: 'com.example.vnewszz.RunnerTests',
  );
}
